### ISSUE TITLE
Use Weblate

### ISSUE THREAD

**Issue by comradekingu** [enz/pentobi#13]
I still get the announcements, even though I stopped using Transifex because I can't accept their terms.
It is one of those fortunate comparisons, where the libre tool is also the better one.
https://hosted.weblate.org/hosting/ or bubu have platforms, and then self-hosting is also possible :)

**Comment by enz** [comment]
I removed you from the Norwegian language members list. That should solve
the problem.
Happy new year anyway.

Markus

**Comment by comradekingu** [comment]
I like seeing the project being active, and using Weblate helps with that.
Happy new year :)

**Comment by enz** [comment]
I tried Weblate a few years ago and it didn't work for me because I needed to contact the admin to add or remove translation components and sometimes my emails to the admin were unanswered for weeks. This is why I moved back to Transifex and why I don't want to have to deal with the admin of Weblate again.

I would be open to the idea that a third person becomes the maintainer of the Pentobi translations if it was a long-term commitment. If you are the only translator of a language, you can also use offline translation tools and commit translation updates via a pull request.

**Comment by comradekingu** [comment]
@enz
It is fully automated via https://hosted.weblate.org/hosting/ now.
If you add "kingu" I can manage/maintain it, or I can set it up and add you. :)

**Comment by enz** [comment]
Honestly, I'm not sure if that sounds like a serious offer to take long-term responsibility for managing the Pentobi translations. Also, is changing the Weblate configuration by users enabled for open-source projects? I remember that later versions of Weblate had a new UI for changing project components by users but the feature was only enabled for "commercial" users.

How about the following proposal: I remove Norwegian from Transifex and you create a Weblate project for it. You can add a description that it is an unofficial repository for Pentobi translations and also accept new languages but only languages that don't exist in Transifex. I will merge the Weblate repository before I do a new Pentobi release.

If everything works well, I will consider moving all languages back to Weblate in a few months should you still be willing to take responsibility for managing the translations.

**Comment by comradekingu** [comment]
Will do.

**Comment by comradekingu** [comment]
@enz I got it to work eventually, but only for all languages.
