### ISSUE TITLE
Using pentobi as an API

### ISSUE THREAD

**Issue by xwkuang5** [enz/pentobi#2]
Hi,

I wonder if there is a link to a document or a way of generating a documentation page that details the use of Pentobi as an API.

Thanks!

**Comment by enz** [comment]
Not much. There is only some documentation on how to use the GTP interface (a high-level command-line interface), see doc/gtp/Pentobi-GTP.html

If you want to use the classes on a C++ level, you probably need to read the source code to fully understand them. You could use Doxygen to generate an HTML reference of the classes, the source code comments use a syntax that is compatible with Doxygen. Or open the project in QtCreator (by opening the main CMakeLists.txt). QtCreator can be used for navigating the source code.

The C++ implementation of the GTP interface can serve as an example how to use the classes to do basic things like initializing a game in a certain game variant, play moves, get the score etc. (see src/libpentobi_base/Engine) and how to use Pentobi's AI to generate a move (see src/libpentobi_mcts/Player and src/pentobi_gtp/Engine).

**Comment by xwkuang5** [comment]
Hi @enz ,

Thank you for your previous reply. The pentobi gtp protocol seems to fit my use case quite well. I want to build a python script to experiment with the pentobi agents (e.g., generating moves from agents with different levels, asking pentobi to rate a move). I found the `twogtp.py` python controller script from `v8`. However, I wasn't able to properly instantiate player agents for the controller. My understanding is that I should invoke the script like this: `python twogtp.py -a -b "/path/to/pentobi-gtp --level 1" -w "/path/to/pentobi-gtp --level 9"`. However, that did not work. 

Can you give an example of how to run the `twogtp` program with two agents (one set to some level and the other one set to some other level)? If the python script is deprecated, can you give an example using the `twogtp` cpp program? They should be the same in terms of passing command arguments, right?

**Comment by enz** [comment]
What OS did you run the Python script on? Were there any error messages?

`twogtp.py` is indeed deprecated and no longer used by me or included in the current Pentobi sources. It has been replaced by the C++ program because I wanted to run some tests on Android and did not want to go through the process of compiling Python for Android.

The C++ program only works on Linux or BSD. There might be minor differences to the Python program. For example, there is no `--alternate` option anymore, it now always alternates the colors if more than one game is played.

Here is an example shell script that I use for playing test games between different versions of Pentobi (the executables for the old and new program are `pentobi.old` and `pentobi.new`):

```
GAME=d
LEVEL=6
NUMBER=1500

./twogtp \
  -b "./pentobi.new -g$GAME -l$LEVEL" \
  -w "./pentobi.old -g$GAME -l$LEVEL" \
  -g$GAME -n$NUMBER --threads 8
```
