### ISSUE TITLE
Documentation and manpage as Weblate resource

### ISSUE THREAD

**Issue by comradekingu** [enz/pentobi#6]
It would be nice to have all resources available for translation.

**Comment by enz** [comment]
True. There is also the desktop and appdata files. Unfortunately, I just found out that while the new Weblate version does support that project owners add new components, this function has been disabled for open-source projects that are not on a billing plan! And after my recent experiences with support tickets at Weblate, I don't feel right now like opening new support tickets right now.

I am also not sure if I want to move some of the files in data to src/pentobi and src/pentobi_kde_thumbnailer, so I better wait until I have decided because changing resource paths would need additional support tickets.

The Pentobi user manual is a bigger problem. Weblate doesn't support translating HTML files. One option would be to convert it to docbook, but that requires some major work.

**Comment by enz** [comment]
I converted the user manual to DocBook format and made it translatable using xml2pot and gettext. A translation component [Pentobi Manual](https://hosted.weblate.org/projects/pentobi/pentobi-manual/) has been added for it at Weblate.

**Comment by comradekingu** [comment]
@enz Nice. Markdown support is about to make its way into Weblate, I volunteered to help with inclusion of projects, but I haven't made it home quite yet.

**Comment by enz** [comment]
Good to know, but there are no markdown files in this project that need to be be translated. Generally, I think all texts visible to end users should be translatable, but it's not worth the effort of creating/maintaining translations for files targeted at developers. Developers should have some basic knowledge of English, otherwise they won't be able to read the comments in the sources anyway.

I'm currently even pondering if the man pages should be translated (or maybe even completely removed from the project) because Pentobi is a desktop application. There is no real need for end users to invoke it from the command line and the command line options of Pentobi are mainly useful for development purposes.

I'm planning to add two more translation components: "Pentobi Unix Files" for the desktop entry, AppData and Shared MIME info in pentobi/unix/, and "Pentobi KDE Thumbnailer" for the MetaInfo file in pentobi_kde_thumbnailer/. BTW, how much are you involved in Weblate? Do you have permissions to add new components in hosted projects?

**Comment by enz** [comment]
The AppData, shared MIME info and manpages are now translatable in pentobi/unix/, pentobi_thumbnailer/ and pentobi_kde_thumbnailer/. I created support tickets at Weblate, so hopefully the new translation components will be added there soon. I'm closing this issue now because I consider it done.
