### ISSUE TITLE
Here are some additional Docbook XSL location hints

### ISSUE THREAD

**Issue by jnumm** [enz/pentobi#8]
Hi!

Distro fragmentation seems to be a real concern with these stylesheets. Two more examples I have seem in the wild:

* Arch Linux: `/usr/share/xml/docbook/xsl-stylesheets-1.79.2`
* Mageia: `/usr/share/sgml/docbook/xsl-stylesheets-1.79.2`

Links to the respective packaging files are here.
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pentobi#n31
http://distrib-coffee.ipsl.jussieu.fr/pub/linux/Mageia/distrib/cauldron/SRPMS/core/release/pentobi-17.3-1.mga8.src.rpm

**Comment by enz** [comment]
I already noticed that almost every distro uses a different location for DocBook XSL. But adding these two paths seems especially brittle because they contain the exact version number, so they are likely to break soon.

The paths hardcoded in Pentobi's FindDocBookXSL.cmake are supposed to be hints only anyway, and the user is supposed to invoke cmake with the option -DDOCBOOKXSL_DIR=… if a different location is used. Some of the packagers patched the cmake file instead, which is unnecessary but also works.

For now, I will add a more detailed error message in FindDocBookXSL.cmake.

**Comment by jnumm** [comment]
I think it's fine to close this ticket if you find these paths are too brittle to add. Packagers can indeed deal with them.
